name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.0.1
      - name: Install dependencies
        run: yarn install
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PESSOALIZE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PESSOALIZE }}
          aws-region: us-east-1
      - name: Deploy to S3 and clear cache in cloud front
        run: CI=false yarn run deploy:production
